development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  database: payment_development
  password: <%= ENV['PAYMENT_DEVELOPMENT_DB_PASSW'] %>

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  database: payment_test
  password: <%= ENV['PAYMENT_DEVELOPMENT_DB_PASSW'] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  database: payment_production
  password: <%= ENV['PAYMENT_PRODUCTION_DB_PASSW'] %>